### ISSUE TITLE
Size is ~3x larger than RocksDB

### ISSUE THREAD

**Issue by vlovich** [dermesser/sstable#11]
May not necessarily be a goal since this follows LevelDB whereas RocksDB chooses a more space efficient layout. I serialize 10 million keys (0 to 10_000_000 serialized as 8 LE bytes). I finish the table every 1 million keys and start a new one. This takes up ~167 MiB and sees to be constant regardless of the key encoding (e.g. not taking the full 8 bytes for smaller keys) or whether or not there's any value stored (e.g. `&[]` is the same 167 MiB as `b"value"`). By comparison, RocksDB uses ~58-70 MiB (varying based on the key serialization and whether or not there's a value).

I'm curious if it's at all interesting to explore what the difference is (using no compression for both RocksDB and SSTable library).

What is interesting is that just filling the SSTable to disk I'm able to get ~40M keys/s for a write-only workload whereas RocksDB shows 80K keys/s but it's unclear to me if that's solely the SSTable at play or because it's a real DB with a memtable level which I ignored for my simple evaluation..

**Comment by dermesser** [comment]
That's indeed very interesting observation. I will try to dig into it in the next couple days.

If you get such a high speed of 40M keys/s, that's probably showing the benefit of building a table in memory and writing it out once, whereas RocksDB would do actual database things. You can compare again with leveldb-rs (also one of my projects), which (in my experience) should be a bit faster than the number you quote for RocksDB. leveldb-rs uses the same data structures as this crate (this crate was decoupled from leveldb-rs at some point).

**Comment by dermesser** [comment]
the first function of interest for you here is probably here: https://github.com/dermesser/sstable/blob/master/src/block_builder.rs#L74

The format for an entry is:

* number of bytes shared with previous key (varint)
* number of bytes not shared with previous key (varint)
* number of bytes in value (varint)
* non-shared bytes of key (bytes)
* value (bytes)

This means: We get somewhat efficient prefix-sharing due to the nice ordering property. However, it means that there is some overhead: 3 bytes for the lengths (assuming small keys/values), then some key bytes, and the value. However, I am confused why you would get the same table size independent of the value.

Did you enable compression, by the way?
